# Generated by Django 6.0.3 on 2026-03-26 08:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('family', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('CPU', 'CPU'), ('GPU', 'GPU'), ('APU', 'APU')], max_length=10)),
                ('socket', models.CharField(max_length=100)),
                ('release_date', models.DateField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('discontinued', 'Discontinued'), ('upcoming', 'Upcoming')], max_length=20)),
            ],
            options={
                'db_table': 'products',
                'ordering': ['-release_date'],
            },
        ),
        migrations.CreateModel(
            name='Firmware',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=100)),
                ('release_date', models.DateField()),
                ('type', models.CharField(choices=[('BIOS', 'BIOS'), ('driver', 'Driver'), ('microcode', 'Microcode')], max_length=20)),
                ('status', models.CharField(choices=[('stable', 'Stable'), ('beta', 'Beta'), ('deprecated', 'Deprecated')], max_length=20)),
                ('changelog', models.TextField(blank=True, default='')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='firmwares', to='api.product')),
            ],
            options={
                'db_table': 'firmwares',
                'ordering': ['-release_date'],
            },
        ),
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recorded_at', models.DateTimeField()),
                ('metric', models.CharField(choices=[('power_consumption', 'Power Consumption'), ('temperature', 'Temperature'), ('clock_speed', 'Clock Speed'), ('utilization', 'Utilization')], max_length=30)),
                ('value', models.FloatField()),
                ('unit', models.CharField(max_length=50)),
                ('firmware', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='api.firmware')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='api.product')),
            ],
            options={
                'db_table': 'statistics',
                'ordering': ['-recorded_at'],
            },
        ),
    ]
