from .basic_class import basic_class
from .basic_class_task import basic_class_task
from .type_hints import type_hints
from .type_hints_task import type_hints_task
from .type_alias import type_alias
from .type_alias_task import type_alias_task
from .union_type import union_type
from .union_type_task import union_type_task
from .dataclass_ import dataclass_
from .dataclass_task import dataclass_task
from .inheritance import inheritance
from .inheritance_task import inheritance_task
