name: Build and Deploy

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js 23.x
        uses: actions/setup-node@v4
        with:
          node-version: 23.x

      - name: npm install and build
        working-directory: ./client
        run: |
          npm install
          npm run build
        env:
          VITE_USE_MOCK: "true"

      - name: Deploy with gh-pages
        working-directory: ./client
        run: |
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          npm run deploy -- -u "github-actions-bot <support+actions@github.com>"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
